import type { Metadata } from "next";
import { Raleway, Lato } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";
import Header from "@/components/header";

const raleway = Raleway({
	variable: "--font-raleway",
	subsets: ["latin"],
});

const lato = Lato({
	variable: "--font-lato",
	weight: ["400"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ViewTransitions>
			<html lang="en">
				<body className={`${raleway.variable} ${lato.variable} antialiased`}>
					<Header />
					{children}
				</body>
			</html>
		</ViewTransitions>
	);
}
